#!/bin/sh

# Go up the directory tree until you arrive to the git root
while [ ! -d .git ]
do
  cd ../
done

#DON'T RUN THE TEST IF WE ARE IN CONTINUOUS_INTEGRATION ENV
if [ "$TRAVIS" = "true" ]; then
   exit 0
fi


files=$(git diff --cached --name-only --diff-filter=ACM | grep "^src/\|test/.*js$")

if [ "$files" = "" ]; then
    exit 0
fi

pass=true
echo "\nRuning Unit Tests:\n"

result="$(gulp test| grep "Error: 1")"

if [ "$result" = "" ]; then
     echo "\t\033[32mUnit Tests Passed\033[0m\n"
else
     echo "\t\033[31mUnit Tests Failed\033[0m\n"
     pass=false
fi

if ! $pass; then
    echo "\t\033[41mPUSH FAILED:\033[0m Your push contains failing tests. Please fix them and try again.\n"
    exit 1
else
    echo "\t\033[42mPUSH SUCCEEDED\033[0m\n"
fi