#!/bin/sh
while [ ! -d .git ]
do
  cd ../
done

#DON'T RUN THE TEST IF WE ARE IN CONTINUOUS_INTEGRATION ENV
if [ "$CONTINUOUS_INTEGRATION" = "true" ]; then
   exit 0
fi

pass=true
echo "\nRuning Unit Tests:\n"

result="$(gulp test| grep "Error: 1")"

if [ "$result" = "" ]; then
     echo "\t\033[32mUnit Tests Passed\033[0m\n"
else
     echo "\t\033[31mUnit Tests Failed\033[0m\n"
     pass=false
fi

if ! $pass; then
    echo "\t\033[41mPUSH FAILED:\033[0m Your push contains failing tests. Please fix them and try again.\n"
    exit 1
else
    echo "\t\033[42mPUSH SUCCEEDED\033[0m\n"
fi