#!/bin/sh
set -e #Quit as soon as there is an error or exit
set -x #Very verbose mode

if [ "$TRAVIS" = "true" ]; then
    if [ -n "$USER_NAME" ]; then
      # inside this git repo we'll pretend to be a new user
      git config --global user.name "$USER_NAME"
      git config --global user.email "$USER_MAIL"
    fi

    if [ "$TRAVIS_BRANCH" = "prerelease" ]; then
        gulp build --env production
        original_dir=`pwd`
        rm -rf /var/tmp/release
        mkdir -p /var/tmp/release
        cd /var/tmp/release
        git clone --branch RELEASE --single-branch --depth 1 "https://$GH_TOKEN@github.com/MailOnline/videojs-vast-vpaid" . &> /dev/null
        old_version=`cat bower.json | grep version | awk -F\" '{print $4}'`
        rsync -a --del --exclude=.git $original_dir/ ./
        git add -A .
        gulp bump --version $old_version
        new_version=`cat bower.json | grep version | awk -F\" '{print $4}'`
        git commit -m "[RELEASE] build and release $new_version"
        git tag $new_version
        git push
        git push --tags
#        gulp deploy-demo
    fi
fi