#!/usr/bin/env bash

#DON'T SETUP THE HOOKS IF YOU ARE IN CI
if [ "$CONTINUOUS_INTEGRATION" != "true" ]; then
  echo "Setting pre-commit hook"
  ln -f -s "$PWD/scripts/pre-commit" .git/hooks/pre-commit

  echo "Setting pre-push hook"
  ln -f -s "$PWD/scripts/pre-push" .git/hooks/pre-push
fi